name: Prueba envio correo
on:
  push:
      branches:
        - main
with:
    # Required mail server address if not connection_url:
    server_address: smtp.gmail.com
    # Server port, default 25:
    server_port: 465
    # Required mail subject:
    subject: Rama Main push
    # Required recipients' addresses:
    to: erickrodriguezgomez04@gmail.com
    # Required sender full name (address can be skipped):
    from: Erick # <user@example.com>
    # Optional plain body:
    body: Build job of ${{github.repository}} completed successfully!