name: Prueba envio correo
on:
  push:
    branches:
      - main

jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar correo
        uses: ErickDarkFire/Practica2@main
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Rama main push"
          to: "erickrodriguezgomez04@gmail.com"
          from: "Erick"
          body: "Build job of ${{ github.repository }} completed successfully!"
