name: Test action externa

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Probar Action externa
        uses: ErickDarkFire/Practica2@main
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Test desde repo externo"
          to: "tuemail@gmail.com"
          from: "Erick"
          body: "Prueba desde otro repositorio"
